### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Lm0611** [SLDGroup/EMCAD#3]
![image](https://github.com/SLDGroup/EMCAD/assets/162393396/ccc909f4-cf7d-4c53-a4d9-a2435e6625c0)
May I ask whether p4 is used as the final segmentation output graph, why not P1，Or why not output=w ×p1+x×p2+y×p3+z×p4

**Comment by mostafij-rahman** [comment]
We use p1 as the final segmentation map. It's reversed in our implementation. Just corrected it, now, you will find the same order.

We avoid using all four outputs because it's difficult to find optimal weights for these outputs.

Thanks for your observation.

Best,
Mostafijur
