### ISSUE TITLE
About ISIC2017 dataset

### ISSUE THREAD

**Issue by melooooody** [SLDGroup/EMCAD#9]
Hi，how was the ISIC2017 dataset prepared in your experiment?

**Comment by tpnam0901** [comment]
Hi @melooooody, you can find this information from the Supplementary Material of the paper 
"We use a train-val-test split of 80:10:10 in ClinicDB, Kvasir, ColonDB, ETIS, BKAI, ISIC18, DSB18, EM, and BUSI datasets. For ISIC17, we use the official train-val-test sets provided by the competition organizer."

**Comment by melooooody** [comment]
OK, thanks for your answer.^_^
